### ISSUE TITLE
### Ideal case for dynamic form field

### ISSUE THREAD

**Issue by rivernews** [rivernews/appl-tracky-spa#19]
How can we get started? Several aspects:

- Dynamically generate field when user touches the last field. We can get started by thinking about how should we provide fieldsProps = [...] with additional information. For example, we might use [{ field1, field2, ... }] in fieldsProps to manifest a dynamic field. 1) The element is an array, 2) the object key-value describes what kind of fields should be created together when adding fields dynamically.

The above leads to another consideration of refactoring how fields should be created:

- Refactoring code for form factory to facilitate DRY code, e.g. initalValues and fieldsProp's name have a lot of repetitive code. How can we let the factory function know how to determine the form name automatically? We may use the field info in data model class, and accept a `exposeFields = {...}` to specify which field should render as form field.

Perhaps a data model, **and a class that can bring data model information into specifying visible/exposed fields and their input type** such as text, date, password or url.

---

The Formik doesn't have good support for `ArrayField` yet, so we better write our own components to handle this.

**Comment by rivernews** [comment]
### Dynamic field creation

How do we achieve this (not considering form or using with Formik)?

- We have a list of fields
- The last field has to be marked as `last`, in some way
- When the last field is touched/value changed, create new field component
    - the field has to have a callback `onTouched` (is dirty). 
    - Once the field is dirty, create new component. This can be achieved by storing field component in a list, and render the list using `map()`. When creating new component, we `push()` to the list. React will update and show the new field then.

**Comment by rivernews** [comment]
![WechatIMG2789](https://user-images.githubusercontent.com/15918424/57075831-f5c94700-6cb5-11e9-856b-4317c776410a.jpeg)

### Execution 

- [ ] Add a "create link" button
- [ ] In the button's onclick callback, push link's field in the form's fieldlist. 
    - Notice that we are doing flattening here. Link has its own fields and ideally should be treated as a form as a whole. Or reframe it as a "model field".
- [ ] Again inn onclick, also augment initialValue. Ideally initialValue shouldn't need to be handled by factory caller, factory should already have such information from the fieldprops info in fieldlist.
- [ ] Test in onSubmit - is the newly created field's value there in formik's value? Is the value reflecting user input change?

**Comment by rivernews** [comment]
### Refactor to using `ModelField`.

Currently we only have `InputField`, where we allow one value at a time, either text, password, date, ...
Now we want `ModelField`, which is a collection of `InputField` that serves for abstraction for data model, but should be used in the same way as `InputField` (should be a kind of `InputField`).

**Comment by rivernews** [comment]
### About how to set Initial value

// TODO

**Comment by rivernews** [comment]
### Add a delete icon to delete link field

### Create new link field when previous link field touched

**Comment by rivernews** [comment]
### Refactor onSubmit

Goal: formfactory lift more responsibility in onSubmit, better for later on generalization as well.
Task 1: refactor to make dynamic form work (just DOM, no need to make API request)
Task 2: test if add/remove field work (just DOM)
Task 3: adapt / test if API request work

---

### Task 1: move onSubmit logic from ASL to form factory

- [ ] LinkFieldProps: implement a function `getModelInstance()`
- [ ] FormFactory: implement a function `onSubmit`, and let `<Formik />` use this on submit.
    - [ ] Such function will loop over fieldPropsList to package each field for API request
    - [ ] Implement form-application-status-link-field if necessary.

# Task 2 & 3

Work on add/remove dynamic field.

- [ ] Test for DOM
- [ ] Test for API request
